### ISSUE TITLE
第三題: Crash 的問題

### ISSUE THREAD

**Issue by the-yuyut** [Jesx/Challenge#2]
https://github.com/Jesx/Challenge/blob/55e55c2570912f2eeae6725ef2b9e84cc16d668a/areaCalculator/areaCalculator/ViewController.swift#L29

很明顯的是這裡的問題

**Comment by Jesx** [comment]
已修復

**Comment by the-yuyut** [comment]
修改 link: 7c1ccd661fc2f89967b054ac01ae46670ee4b2af
不錯的練習
