### ISSUE TITLE
第四題: 請考慮 if let

### ISSUE THREAD

**Issue by the-yuyut** [Jesx/Challenge#3]
https://github.com/Jesx/Challenge/blob/55e55c2570912f2eeae6725ef2b9e84cc16d668a/Discount/Discount/ViewController.swift#L23

`if let oriNum = Float(oriPrice.text){ ... }`

**Comment by Jesx** [comment]
已更改

**Comment by the-yuyut** [comment]
修改 link: ec027520c93c6eb00d362e8e48f4d9a22809d887 
有很多範例是使用 `if let`, 可以減少閱讀的量
